import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { Pressable, StyleSheet, Text, TextInput, View, type TextInputProps, type PressableProps } from "react-native";

export function AppHeader({ eyebrow, title, subtitle, action }: { eyebrow?: string; title: string; subtitle?: string; action?: React.ReactNode }) {
  const colors = useColors();
  return <View style={styles.header}><View style={styles.headerCopy}>{eyebrow ? <Text style={[styles.eyebrow, { color: colors.primary }]}>{eyebrow.toUpperCase()} <Text style={[styles.dot, { color: colors.success }]}>✦</Text></Text> : null}<Text style={[styles.title, { color: colors.foreground }]}>{title}</Text>{subtitle ? <Text style={[styles.subtitle, { color: colors.muted }]}>{subtitle}</Text> : null}</View>{action}</View>;
}
export function Surface({ children, style }: { children: React.ReactNode; style?: object }) { const colors = useColors(); return <View style={[styles.surface, { backgroundColor: colors.surface, borderColor: colors.border }, style]}>{children}</View>; }
export function SectionTitle({ title, action }: { title: string; action?: React.ReactNode }) { const colors = useColors(); return <View style={styles.sectionTitle}><Text style={[styles.sectionTitleText, { color: colors.foreground }]}>{title}</Text>{action}</View>; }
export function PrimaryButton({ label, icon = "plus", onPress, disabled }: { label: string; icon?: "plus" | "checkmark.circle.fill" | "arrow.clockwise" | "paperplane.fill"; onPress?: PressableProps["onPress"]; disabled?: boolean }) { const colors = useColors(); return <Pressable accessibilityRole="button" onPress={onPress} disabled={disabled} style={({ pressed }) => [styles.primaryButton, { backgroundColor: colors.primary, borderColor: colors.primary, shadowColor: colors.primary }, pressed && styles.pressed, disabled && styles.disabled]}><IconSymbol name={icon} size={17} color={colors.onPrimary} /><Text style={[styles.primaryButtonText, { color: colors.onPrimary }]}>{label}</Text></Pressable>; }
export function GhostButton({ label, icon, onPress }: { label: string; icon?: "pencil" | "calendar" | "bell.fill" | "gearshape.fill"; onPress?: PressableProps["onPress"] }) { const colors = useColors(); return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.ghostButton, { borderColor: colors.border, backgroundColor: colors.surface }, pressed && styles.pressed]}>{icon ? <IconSymbol name={icon} size={16} color={colors.foreground} /> : null}<Text style={[styles.ghostButtonText, { color: colors.foreground }]}>{label}</Text></Pressable>; }
export function Field({ label, style, ...props }: TextInputProps & { label: string; style?: object }) { const colors = useColors(); return <View style={styles.fieldWrap}><Text style={[styles.fieldLabel, { color: colors.muted }]}>{label}</Text><TextInput placeholderTextColor={colors.muted} selectionColor={colors.primary} style={[styles.field, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }, style]} {...props} /></View>; }
export function Chip({ label, active, onPress }: { label: string; active?: boolean; onPress?: () => void }) { const colors = useColors(); return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.chip, { borderColor: active ? colors.primary : colors.border, backgroundColor: active ? colors.primary : colors.surface }]}><Text style={[styles.chipText, { color: active ? colors.onPrimary : colors.muted }]}>{label}</Text></Pressable>; }
export function EmptyState({ icon, title, body }: { icon: "creditcard.fill" | "chart.line.uptrend.xyaxis" | "lock.fill" | "calendar" | "sparkles"; title: string; body: string }) { const colors = useColors(); return <View style={[styles.empty, { borderColor: colors.border, backgroundColor: colors.surface }]}><View style={[styles.emptyIcon, { backgroundColor: colors.primary }]}><IconSymbol name={icon} size={24} color={colors.onPrimary} /></View><Text style={[styles.emptyTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.emptyBody, { color: colors.muted }]}>{body}</Text></View>; }
export const styles = StyleSheet.create({
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24 }, headerCopy: { flex: 1, paddingRight: 12 }, eyebrow: { fontSize: 10, fontWeight: "900", letterSpacing: 2, marginBottom: 9 }, dot: { fontSize: 10 }, title: { fontSize: 34, fontWeight: "900", letterSpacing: -1.4, lineHeight: 38 }, subtitle: { fontSize: 13, lineHeight: 19, marginTop: 8, maxWidth: 310 }, surface: { borderRadius: 22, padding: 18, borderWidth: 1 }, sectionTitle: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 28, marginBottom: 12 }, sectionTitleText: { fontSize: 17, fontWeight: "900", letterSpacing: -0.3 }, primaryButton: { minHeight: 50, borderRadius: 15, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderWidth: 1, shadowOpacity: 0.22, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 3 }, primaryButtonText: { fontWeight: "900", fontSize: 13, letterSpacing: 0.2 }, ghostButton: { minHeight: 40, borderRadius: 13, borderWidth: 1, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 }, ghostButtonText: { fontWeight: "800", fontSize: 12 }, pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] }, disabled: { opacity: 0.45 }, fieldWrap: { marginBottom: 13 }, fieldLabel: { fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginBottom: 7, textTransform: "uppercase" }, field: { minHeight: 50, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, fontSize: 15 }, chip: { borderWidth: 1, paddingHorizontal: 14, paddingVertical: 9, borderRadius: 999, marginRight: 8 }, chipText: { fontSize: 11, fontWeight: "900" }, empty: { minHeight: 190, borderWidth: 1, borderStyle: "dashed", borderRadius: 22, padding: 22, justifyContent: "center", alignItems: "center" }, emptyIcon: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center", marginBottom: 13 }, emptyTitle: { fontWeight: "900", fontSize: 16, textAlign: "center" }, emptyBody: { lineHeight: 19, fontSize: 13, textAlign: "center", marginTop: 7, maxWidth: 280 }, fab: { width: 45, height: 45, borderRadius: 999, alignItems: "center", justifyContent: "center" }, headerCreate: { minHeight: 44, borderRadius: 14, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 }, calendarArrow: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center" },
});
